// Usage: pnpm gen:api [spec-url-or-file]. Keeps only the GET operations the web client consumes.
import { readFileSync, writeFileSync } from 'node:fs';
import openapiTS, { astToString } from 'openapi-typescript';

const canonical = 'https://huggingface.co/.well-known/openapi.json';
const source = process.argv[2] ?? canonical;
const target = new URL('../src/lib/api/hf-openapi.d.ts', import.meta.url);

const keep = [
	'/api/models/{namespace}/{repo}/tree/{rev}/{path}',
	'/api/models/{namespace}/{repo}/refs',
	'/api/models/{namespace}/{repo}/commits/{rev}',
	'/api/models/{namespace}/{repo}/compare/{compare}',
	'/api/models-tags-by-type',
	'/api/datasets-tags-by-type',
	'/api/quicksearch',
	'/api/users/{username}/overview',
	'/api/whoami-v2'
];

const spec = /^https?:/.test(source)
	? await (await fetch(source)).json()
	: JSON.parse(readFileSync(source, 'utf8'));

const missing = keep.filter((path) => !spec.paths?.[path]?.get);
if (missing.length) throw new Error(`spec lacks GET operations for: ${missing.join(', ')}`);

spec.paths = Object.fromEntries(keep.map((path) => [path, { get: spec.paths[path].get }]));

const ast = await openapiTS(spec);
writeFileSync(
	target,
	`// Generated by tools/gen-api.ts (pnpm gen:api) from ${canonical}; do not edit.\n\n${astToString(ast)}`
);
console.log(`wrote ${target.pathname} (${keep.length} operations)`);
